### ISSUE TITLE
Admin panel + API

### ISSUE THREAD

**Issue by dzucconi** [artsy/places#8]
So my current thinking about this repo/module is that: it's hard to manage, and it's inefficient. We just arbitrarily execute some code when it's required and load all the data into memory, not great.

On Friday I slapped together a admin panel app for this and figured that we can just serve the data through a little API and cache it with a long expiry.

Before I get too deep into that though I was considering an alternative to running an actual server:

Use http://geojson.io/ to edit place geometry. We can authenticate with Github through that and store the geojson files in this repo. [Github has nice support for geojson.](https://github.com/blog/1528-there-s-a-map-for-that).

We can then just write a simple build process that deploys the JSON to S3/Cloudfront and just treat that as our 'API'

**Comment by anandaroop** [comment]
I think storing the data as GeoJSON makes a huge amount of sense, since it will get you many things for free such as:
- map-based previewing in Github.
- easy interoperability with other mapping libs such as D3, Leaflet, etc

The map preview alone would be immediately worthwhile since it will immediately surface problems such as the recent Moscow error.

Right now you'd have to go through a couple of hoops to plot the locations and do ground-truthing. 

(I did... and **Daegu** and **Mumbai** are misplaced as well :grimacing:)
